### ISSUE TITLE
socketio.exceptions.ConnectionError: Connection refused by the server

### ISSUE THREAD

**Issue by geniuslwy** [fxcm/RestAPI#102]
Traceback (most recent call last):
  File "D:/RestAPI-master/fxcm-api-rest-python3-example/get_historydata.py", line 12, in <module>
    trader.login()
  File "D:\RestAPI-master\fxcm-api-rest-python3-example\fxcm_rest_api_token.py", line 123, in login
    self.socketIO.connect(self.environment.get("trading") +':'+ str(self.environment.get("port")) + '/?access_token='+  self.access_token)
  File "D:\anaconda3\envs\fxcm-api-rest-python3-example\lib\site-packages\socketio\client.py", line 280, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection refused by the server

How can I solve this problem？
![image](https://user-images.githubusercontent.com/76502118/103192267-0d395700-4913-11eb-8a82-68fb74e6e2cc.png)

**Comment by fxcm-dhalpert** [comment]
Please check if current version of python-engineio is 4 then install 3.9
To check the current version of python-engineio, from CMD:
python -c "import engineio; print(engineio.__version__)"
to install it:
python -m pip install python-engineio==3.9
