### ISSUE TITLE
Socket returns unknown error. 

### ISSUE THREAD

**Issue by juannieblas** [fxcm/RestAPI#104]
I have the same iissue that #100 
I tried downgrade socketio version to 4.6.1 but the issue continue
```
import fxcmpy
import socketio
TOKEN = 'Token'
print(fxcmpy.__version__)
print(socketio.__version__)

con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
print(con.get_instruments())
```

output
```
1.2.6
4.6.1
Traceback (most recent call last):
  File ".\main.py", line 7, in <module>
    con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
  File "C:\Users\juanp\AppData\Local\Programs\Python\Python38\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
```

**Comment by juannieblas** [comment]
Sorry duplicated #105
