### ISSUE TITLE
Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by juannieblas** [fxcm/RestAPI#105]
I have the same iissue that #100 
I tried downgrade socketio version to 4.6.1 but the issue continue
```
import fxcmpy
import socketio
TOKEN = 'Token'
print(fxcmpy.__version__)
print(socketio.__version__)

con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
print(con.get_instruments())
```

output
```
1.2.6
4.6.1
Traceback (most recent call last):
  File ".\main.py", line 7, in <module>
    con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
  File "C:\Users\juanp\AppData\Local\Programs\Python\Python38\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
```

**Comment by juannieblas** [comment]
log
```
|INFO|2021-01-08 10:35:34,754|Connecting FXCM Server
|DEBUG|2021-01-08 10:35:34,755|Access token: 1e50ecce5aa299d779869a8cc4f69c4518caadfb.
|DEBUG|2021-01-08 10:35:34,759|Starting new HTTPS connection (1): api-demo.fxcm.com:443
|ERROR|2021-01-08 10:35:34,825|Socket returns unknown error.

```

**Comment by juannieblas** [comment]
log```

|INFO|2021-01-08 10:35:34,754|Connecting FXCM Server
|DEBUG|2021-01-08 10:35:34,755|Access token: token.
|DEBUG|2021-01-08 10:35:34,759|Starting new HTTPS connection (1): api-demo.fxcm.com:443
|ERROR|2021-01-08 10:35:34,825|Socket returns unknown error.

```

**Comment by juannieblas** [comment]
I tried with socketio 4.4.0 and works well
