### ISSUE TITLE
PFX Error on connection

### ISSUE THREAD

**Issue by benjamin-fukdawurld** [fxcm/RestAPI#118]
I cloned the code and ran `npm install` and when I try to run the code with `node main.js`

I get this in the console:
```
> Socket.IO session connect error:  Error: xhr poll error
    at XHR.Transport.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transport.js:64:13)
    at Request.<anonymous> (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:129:10)
    at Request.Emitter.emit (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:307:8)
    at Timeout._onTimeout (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:267:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
      at Object.createSecureContext (node:_tls_common:333:17)
      at Object.connect (node:_tls_wrap:1601:48)
      at Agent.createConnection (node:https:130:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:314:16)
      at request (node:https:326:10)
      at XMLHttpRequest.send (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:494:17)
      at Request.create (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:261:9)
      at new Request (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:166:8) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
Socket.IO session connect error:  Error: xhr poll error
    at XHR.Transport.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transport.js:64:13)
    at Request.<anonymous> (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:129:10)
    at Request.Emitter.emit (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:307:8)
    at Timeout._onTimeout (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:267:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
      at Object.createSecureContext (node:_tls_common:333:17)
      at Object.connect (node:_tls_wrap:1601:48)
      at Agent.createConnection (node:https:130:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:314:16)
      at request (node:https:326:10)
      at XMLHttpRequest.send (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:494:17)
      at Request.create (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:261:9)
      at new Request (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:166:8) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
```

When I use 'http' instead of https I get this result:
```
> Socket.IO session connect error:  Error: xhr poll error
    at XHR.Transport.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transport.js:64:13)
    at Request.<anonymous> (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:129:10)
    at Request.Emitter.emit (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:307:8)
    at Timeout._onTimeout (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:254:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: 400
}
Socket.IO session connect error:  Error: xhr poll error
    at XHR.Transport.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transport.js:64:13)
    at Request.<anonymous> (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:129:10)
    at Request.Emitter.emit (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:307:8)
    at Timeout._onTimeout (/home/altim/dev/personel/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:254:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: 400
}
```

**Comment by fxcm-dhalpert** [comment]
if this issue still exists please email the username and related snip code to api@fxcm.com

**Comment by subenksaha** [comment]
Upgrade socket io client version. mine is working for
"socket.io-client": "^4.5.1"
