### ISSUE TITLE
Python wrapper connection broken

### ISSUE THREAD

**Issue by riodda** [fxcm/RestAPI#119]
Tryed to use the samples but got error (<toekn> is my actual demo token).
````
import fxcmpy
import socketio
import pandas as pd
import datetime as dt
from datetime import datetime
TOKEN = '<token>'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
instruments = con.get_instruments()
print(instruments)
````
Returns this error

````
|ERROR|2021-02-27 15:32:29,221|Socket returns unknown error.
---------------------------------------------------------------------------
ServerError                               Traceback (most recent call last)
<ipython-input-5-14c905c31416> in <module>
      5 from datetime import datetime
      6 TOKEN = '<token>'
----> 7 con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
      8 #instruments = con.get_instruments()
      9 #print(instruments)

H:\anaconda3\envs\plaid-ml\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.
````
fxcmpy.__version__ is 5.0.4

**Comment by riodda** [comment]
Tested on a different machine (Linux), still the same error
````
|INFO|2021-02-27 16:23:42,142|Connecting FXCM Server
|DEBUG|2021-02-27 16:23:42,142|Access token: 0ac0d0560d766ef1492ab6e5eab3eee569a71769.
|DEBUG|2021-02-27 16:23:42,149|Starting new HTTPS connection (1): api-demo.fxcm.com:443
|DEBUG|2021-02-27 16:23:42,432|https://api-demo.fxcm.com:443 "GET /socket.io/?access_token=<token>&agent=pythonquants&wait_for_connection=False&transport=polling&EIO=4&t=1614439422.143591 HTTP/1.1" 200 None
|ERROR|2021-02-27 16:23:42,436|Socket returns unknown error.
Traceback (most recent call last):
  File "./renko_test.py", line 18, in <module>
    con = fxcmpy.fxcmpy(access_token='<token>', log_level='debug',server='demo')
  File "/home/dario/.local/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
````
Tyred also demo2 server but same problem

**Comment by fxcm-dhalpert** [comment]
Please check if current version of python-engineio is 4 then install 3.9
To check the current version of python-engineio, from CMD:
python -c "import engineio; print(engineio.__version__)"
to install it:
python -m pip install python-engineio==3.9

**Comment by riodda** [comment]
````
(plaid-ml) PS C:\Windows\system32> python -c "import engineio; print(engineio.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'engineio' has no attribute 'version'
(plaid-ml) PS C:\Windows\system32> python -m pip install python-engineio==3.9
Collecting python-engineio==3.9
  Downloading python_engineio-3.9.0-py2.py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 6.8 MB/s
Requirement already satisfied: six>=1.9.0 in h:\anaconda3\envs\plaid-ml\lib\site-packages (from python-engineio==3.9) (1.15.0)
Installing collected packages: python-engineio
  Attempting uninstall: python-engineio
    Found existing installation: python-engineio 4.0.0
    Uninstalling python-engineio-4.0.0:
      Successfully uninstalled python-engineio-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-socketio 5.0.4 requires python-engineio>=4, but you have python-engineio 3.9.0 which is incompatible.
Successfully installed python-engineio-3.9.0
(plaid-ml) PS C:\Windows\system32>
````

Now the error on the code is different
````
runfile('H:/anaconda3/envs/plaid-ml/lib/site-packages/fxcmpy/fxcmpy.py', wdir='H:/anaconda3/envs/plaid-ml/lib/site-packages/fxcmpy')
Traceback (most recent call last):

  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\fxcmpy\fxcmpy.py", line 24, in <module>
    import fxcmpy.fxcmpy_instruments as fxcmpy_instruments

  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\fxcmpy\fxcmpy.py", line 24, in <module>
    import fxcmpy.fxcmpy_instruments as fxcmpy_instruments

ModuleNotFoundError: No module named 'fxcmpy.fxcmpy_instruments'; 'fxcmpy' is not a package
````
