### ISSUE TITLE
NodeJS Socket.IO session connect error:  Error: server error

### ISSUE THREAD

**Issue by aswanevelder** [fxcm/RestAPI#143]
Is my config wrong for a demo test?

```
config.token = "valid token"; // get this from http://tradingstation.fxcm.com/
config.trading_api_host = 'api-demo.fxcm.com';
config.trading_api_port = 443;
config.trading_api_proto = 'https'; // http or https
```

Error I am getting running node main.js

```
Socket.IO session connect error:  Error: server error
    at Socket.onPacket (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/socket.js:393:23)
    at XHR.Emitter.emit (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:145:20)
    at XHR.onPacket (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transport.js:105:10)
    at callback (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling.js:98:12)
    at Array.forEach (<anonymous>)
    at XHR.onData (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling.js:102:56)
    at Request.Emitter.emit (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/component-emitter/index.js:145:20)
    at Request.onData (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:231:10)
    at Request.onLoad (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:282:12)
    at XMLHttpRequest.xhr.onreadystatechange (/Users/antonswanevelder/_learn/RestAPI/fxcm-api-rest-nodejs-example/node_modules/engine.io-client/lib/transports/polling-xhr.js:186:18) {
  code: 'parser error'
```
package.json

```
"dependencies": {
		"socket.io": "^1.7.3",
		"socket.io-client": "^4.1.2"
	},
```

**Comment by FXCMAPI** [comment]
![image](https://user-images.githubusercontent.com/13039151/119403221-fde4ec80-bcab-11eb-9a58-cac68f5f007f.png)

**Comment by aswanevelder** [comment]
Thank you, I updated the packages to avoid vulnerabilities but the example only works with socket-io-client@1.7.3

```
"dependencies": {
		"socket.io-client": "^1.7.3"
	}
```
