### ISSUE TITLE
Error connecting to the server

### ISSUE THREAD

**Issue by 69ways** [fxcm/RestAPI#159]
`import fxcmpy
import socketio
import engineio
print(fxcmpy.__version__)
print(socketio.__version__)
print(engineio.__version__)
TOKEN = "56ea7dc9b5cd22474ae712bd98162d7212140520"
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error')
print(con.get_instruments())`

Output:
> 1.2.9
4.6.1
3.14.2
|ERROR|2021-07-26 09:49:46,799|Connection error: None
|ERROR|2021-07-26 09:49:46,800|Socket returns unknown error.
|ERROR|2021-07-26 09:49:46,800|Connection aborted, failed to reconnect
[]

I was able to get the instruments symbols before and establish connection with the server before but it doesn't work today. I updated the token and tried again and it still doesn't work. Please help

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Try with:
python -m pip install websocket-client

**Comment by 69ways** [comment]
> Hi,
> 
> Try with:
> python -m pip install websocket-client

Hi,

Output:
`Requirement already satisfied: websocket-client in ./venv/lib/python3.8/site-packages (1.1.0)`

Many thanks

**Comment by 69ways** [comment]
Update:

It works in jupyter but not in pycharm

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Maybe try with downgrading fxcmpy to 1.2.6?

**Comment by 69ways** [comment]
Hi,

It suddenly stopped working on jupyter and I typed 

`pip install fxcmpy==1.2.6`

for both of them and both jupyter and pycharm showed the same error

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Okay, in such case I'd recommend for both pycharm and jupyter:
pip install fxcmpy==1.2.9
pip install python-socketio==4.4
pip install python-engineio==3.9
pip install websocket-client==1.1.0

Also please make sure that you don't have socketio-client package:
pip uninstall socketio-client

**Comment by 69ways** [comment]
> pip install websocket-client==1.1.0

Hello,

Still I'm getting the error after uninstalling and reinstalling all the packages, getting a new token and restarting the IDE

> |ERROR|2021-07-26 12:43:40,251|Socket returns unknown error.
Traceback (most recent call last):
  File "/Users//PycharmProjects/Algo/FXCM/Test.py", line 15, in <module>
    con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error')
  File "/Users//PycharmProjects/Algo/venv/lib/python3.8/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please share your token at api@fxcm.com
