### ISSUE TITLE
Connection aborted, failed to reconnect

### ISSUE THREAD

**Issue by Czollli** [fxcm/RestAPI#167]
Hi,

Python version: 3.9.7
Fxcmpy version: 1.2.9

my stripped down test code is

`import fxcmpy

con = fxcmpy.fxcmpy(config_file='fxcm.cfg')

if con.is_connected() == True:
  print('Connected')

con.close()
`
and the output

Traceback (most recent call last):
  File "/home/zoltan/MY_PROJECTS/fxcm/myfxcm.py", line 5, in <module>
    con = fxcmpy.fxcmpy(config_file='fxcm.cfg')
  File "/home/zoltan/.pyenv/versions/py39/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 226, in __init__
    self.__collect_offers__()
  File "/home/zoltan/.pyenv/versions/py39/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 2284, in __collect_offers__
    offers = self.get_offers('list')
  File "/home/zoltan/.pyenv/versions/py39/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 412, in get_offers
    data = self.get_model(('Offer',))
  File "/home/zoltan/.pyenv/versions/py39/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 344, in get_model
    data = self.__handle_request__(method='trading/get_model',
  File "/home/zoltan/.pyenv/versions/py39/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect

I also use the slightly modified version of test code from [here](https://github.com/fxcm/RestAPI/issues/132) 
but connection has not been established...

(py39) zoltan@zorro:/MY_PROJECTS/fxcm$ python fxcm-test-2.py 
Python version: 3.9.7 (default, Sep 21 2021, 12:25:35) 
[GCC 8.3.0]
xo5_R6Cif_tFzAtVAhWS
Bearer xo5_R6Cif_tFzAtVAhWS10d5d89f383b38f409b779ef618cac2f07eb6f0d
(py39) zoltan@zorro:~/MY_PROJECTS/fxcm$

I use the following package versions

`
(py39) zoltan@macar:~/MY_PROJECTS/fxcm$ pip list
Package            Version
------------------ ---------
bidict             0.21.3
certifi            2021.5.30
charset-normalizer 2.0.6
configparser       5.0.2
fxcmpy             1.2.9
idna               3.2
numpy              1.21.2
pandas             1.3.3
pip                21.2.3
PySocks            1.7.1
python-dateutil    2.8.2
python-engineio    3.9.0
python-socketio    4.6.0
pytz               2021.1
requests           2.26.0
setuptools         57.4.0
six                1.16.0
urllib3            1.26.6
`
I tried with Python 3.8 and 3.7 with the same result.

Any idea how to fix it?

Thanks

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please install websocket-client:
python -m pip install websocket-client

**Comment by Czollli** [comment]
Hi,

Thank you for your quick response.

The first code now says

Traceback (most recent call last):
  File "/home/zoltan/MY_DOCKER_PROJECTS/fxcm/myfxcm.py", line 5, in <module>
    con = fxcmpy.fxcmpy(config_file='fxcm.cfg')
  File "/home/zoltan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.


The second

Python version: 3.9.7 (default, Sep 21 2021, 12:25:35) 
[GCC 8.3.0]
Traceback (most recent call last):
  File "/home/zoltan/MY_DOCKER_PROJECTS/fxcm/fxcm-test-2.py", line 33, in <module>
    socketIO.connect(TRADING_API_URL + ":" + str(WEBSOCKET_PORT) + "/?access_token=" + ACCESS_TOKEN)
  File "/home/zoltan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/socketio/client.py", line 329, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: OPEN packet not returned by server

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Try without configuration file:
con = fxcmpy.fxcmpy(access_token=your token, log_level='debug', log_file='log.txt')

If it still doesn't work please share your account number / token at api@fxcm.com

**Comment by Czollli** [comment]
Hi, 

still the same with both codes as in the opening post after downgrading socketio
pip install python-socketio==4.6.1

so I am e-mailing you my details.

Thanks

**Comment by Czollli** [comment]
Hi,

I figured out the fix.
In a fresh clean python environment 'pip install fxcmpy' (installing version 1.2.9) does not work however
it installs necessary packages which are missing if I install previous version 'pip install fxcmpy==1.2.8' first.

So my steps were:
pip install fxcmpy
pip install python-socketio==4.6.1
pip install fxcmpy==1.2.8

because it does not work with latest (atm 5.4.0) python-socketio.
I have not tested through all variations of v5.x but with those I did it failed to work.

I hope this helps someone.

**Comment by FXCM-ValentinMandev** [comment]
Thank you for sharing this.

**Comment by imadmoussa1** [comment]
> Hi,
> 
> I figured out the fix.
> In a fresh clean python environment 'pip install fxcmpy' (installing version 1.2.9) does not work however
> it installs necessary packages which are missing if I install previous version 'pip install fxcmpy==1.2.8' first.
> 
> So my steps were:
> pip install fxcmpy
> pip install python-socketio==4.6.1
> pip install fxcmpy==1.2.8
> 
> because it does not work with latest (atm 5.4.0) python-socketio.
> I have not tested through all variations of v5.x but with those I did it failed to work.
> 
> I hope this helps someone.

Hello, I am using the same python and fxcmpy version. when I run my script I am connected and everything works fine, but if the internet is down I can't reconnect automatically without stopping the script and run it again. I tried your solution but did not work.
I have this error: 
```
/python3.9/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
````
and this is my code to reconnect to service if lost internet:
```
print(_con.is_connected())
_con.close()
_con = fxcmpy.fxcmpy(config_file=_config_file, server=_server)
```

**Comment by Czollli** [comment]
Hi,

TBH I just started using the api and I am still using it with my demo account which works fine.

I do not specify server though

```
con.close()

_con = fxcmpy.fxcmpy(config_file='fxcm.cfg')
print(_con.is_connected())
```
Not sure if this is the reason or the above.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

The default value for server is 'demo', so it only needs to be specified when connecting with real account.

When re-connecting previous session might still not be finalized on our server side, so I would suggest adding sleep timer for 30 or 60 seconds.

Best Regards,
Valentin

**Comment by imadmoussa1** [comment]
Hello, 
Yes, I am still using the demo server, but I added the variable to set the value real from my app faster.
I will test a sleep timer when the connection fails.

Thank you

**Comment by imadmoussa1** [comment]
Hello, after adding a sleep timer for 60 seconds nothing changed.
I tracked the in the fxcm.py file and commented on some logs error, I was able to found the error origin
```
Traceback (most recent call last):
  File "python3.9/site-packages/fxcmpy/fxcmpy.py", line 2350, in __connect__
    socketIO.connect(self.trading_url+':443' +"/?access_token=" + self.access_token + '&agent=pythonquants&wait_for_connection=False')
  File "python3.9/site-packages/socketio/client.py", line 280, in connect
    self.eio.connect(url, headers=headers, transports=transports,
  File "python3.9/site-packages/engineio/client.py", line 183, in connect
    raise ValueError('Client is not in a disconnected state')
ValueError: Client is not in a disconnected state
```
Versions of :
python-engineio==3.14.2
python-socketio==4.6.1

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please check if you have socketio-client installed and remove it if you have it.
