### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by gpmn** [fxcm/RestAPI#17]
I do nothing, just call these three function then study the offer's field, and let the console alone.
>>> pd.set_option('display.max_columns',500)
>>> pd.set_option('display.width',1000)
>>> conn.get_offers(kind='dataframe')

After about one hour or more, it raised an exception like this:

>>> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpmn/.local/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 2364, in __connect__
    self.socket.wait()
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 276, in _process_packets
    for engineIO_packet in self._transport.recv_packet():
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/transports.py", line 158, in recv_packet
    packet_text)
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/parsers.py", line 96, in parse_packet_text
    packet_type = int(get_character(packet_text, 0))
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/symmetries.py", line 33, in get_character
    return chr(get_byte(x, index))
  File "/home/gpmn/.local/lib/python3.6/site-packages/socketIO_client/symmetries.py", line 29, in get_byte
    return indexbytes(x, index)
IndexError: index out of range

**Comment by FXCMAPI** [comment]
looks like issue is from third party software socketIO_client. 
if you don't expect data push to your side via socket. i suggest you close your socket after the retrieval. and re-connect it again when you need 

thanks
Lei
