### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by munhod** [fxcm/RestAPI#25]
hi, Please help!
After working for a little while, the connection closes when trying to make an order or close an order at this part of the code:

order = con.open_trade('EUR/USD', is_buy=False, amount=myorder, time_in_force='GTC', 
                                       order_type='AtMarket', is_in_pips=True, account_id = account_id[0])

**Error:**
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 2377, in __connect__
    self.socket.wait()
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 2559, in __on_price_update__
    callbacks[func](data, self.prices[symbol])
  File "<ipython-input-10-117cd4669d8f>", line 60, in plot_data
    order_type='AtMarket', is_in_pips=True, account_id = account_id[0])
  File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 1132, in open_trade
    params=params, protocol='post')
  File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 2475, in __handle_request__
    proxies=self.proxies)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by FXCMAPI** [comment]
looks like it is a connection error. maybe due to session lost. 
since you are the initiator, you may need to monitor and make re-connect when necessary.

**Comment by munhod** [comment]
Thanks!
you mean something like this?

if not con.is_connected():
     con = fxcmpy.fxcmpy(config_file= 'fxcm.cfg')

**Comment by FXCMAPI** [comment]
yes, for connection, i suggest you try below

TOKEN = 'your token'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='real', log_file='log.txt')

**Comment by munhod** [comment]
Thank you!
