### ISSUE TITLE
Fail to open trade with the nodejs demo code

### ISSUE THREAD

**Issue by jjqqkk** [fxcm/RestAPI#40]
Hi, i'm testing the nodejs demo code, with my own demo account token. 

Login works fine. "/trading/get_model" works fine. But "/trading/open_trade" never got executed. The error message:

execution error: 0  :  { Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }

**Comment by jjqqkk** [comment]
oh i was using a wrong account_id in the request.. now it is working fine. Ticket closed, thanks for making such an interesting API.
